### ISSUE TITLE
I'm not getting any suggestions 

### ISSUE THREAD

**Issue by danielo515** [unsplash/ts-namespace-import-plugin#12]
Hello, thanks for what looks like a great idea. 
I configured it for fp-ts following the docs, but I am,not getting any suggestions in VSCode. Is there any way I can debug it?

**Comment by danielo515** [comment]
Just in case you missed my question

**Comment by MrFunctor** [comment]
Hello :wave: 
This could be happening because you are using VSCode's version of TypeScript. In that case, you should switch to the workspace version of TypeScript. You can do that by pressing Ctrl/Cmd + Shift + P, then running the **TypeScript: Select TypeScript Version** command, and selecting **Use Workspace Version**. Then, you might have to restart VSCode to start seeing the import suggestions. Let me know if that fixes the problem for you. 🙂

**Comment by danielo515** [comment]
That was indeed the problem. I tested your solution and works like a charm, thank you
